name: Build Nextjs Boilerplate Template without Surf  Frontend

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}
    defaults:
      run:
        working-directory: ./templates/nextjs-boilerplate-template
    steps:
      - uses: actions/checkout@v3

      # Remove surf related files
      - run: rm ./src/Components/MessageBoardWithSurf.tsx
      - run: rm ./src/Components/TransferAPTWithSurf.tsx
      - run: rm -rf ./src/view-functions-with-surf
      - run: rm ./src/utils/surf_client.ts

      # Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
          run_install: false

      # Install deps and build.
      - run: pnpm install
      - run: CI= pnpm build

      # Verify that the format is correct
      - run: npm run _fmt -- --check
        shell: bash
