name: Build Boilerplate Template with Surf Frontend

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}-${{ github.workflow }}
    defaults:
      run:
        working-directory: ./templates/boilerplate-template
    steps:
      - uses: actions/checkout@v3

      # Install pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
          run_install: false

      # Handle surf related files
      - run: rm -rf ./frontend/entry-functions
      - run: rm -rf ./frontend/view-functions
      - run: ls ./frontend
      - run: mv ./frontend/components/MessageBoardWithSurf.tsx ./frontend/components/MessageBoard.tsx
      - run: mv ./frontend/components/TransferAPTWithSurf.tsx ./frontend/components/TransferAPT.tsx
      - run: mv ./frontend/view-functions-with-surf ./frontend/view-functions

      # Install deps and build.
      - run: pnpm install
      - run: pnpm install @thalalabs/surf
      - run: CI= pnpm build

      # Verify that the format is correct
      - run: npm run _fmt -- --check
        shell: bash
